### ISSUE TITLE
ref tags are not identified and therefore the use of them may output incorrect warnings

### ISSUE THREAD

**Issue by bondib** [MeirionHughes/aurelia-template-lint#119]
I get:

[19:05:10] WARNING: cannot find 'ddDashboardListButtonRef' in type 'Index' Ln 19 Col 21 /src/dashboard/index.html

for the following html:

`  <button click.delegate="onDashboardListDDClick(ddDashboardListButtonRef.attributes['aria-expanded'].value)" id="ddDashboardList"
                        ref="ddDashboardListButtonRef" type="button" class="btn btn-sm btn-default dropdown-toggle" data-toggle="dropdown">
                            
                            <i if.bind="loadingSelectedDashboard" class="fa fa-refresh fa-spin"></i>
                            <span if.bind="(!currentSelectedDashboard || currentSelectedDashboard == null)">--------------------------------</span>
                            <span if.bind="currentSelectedDashboard">${currentSelectedDashboard.entity.name}</span><i class="fa fa-angle-down"></i>
                        </button>`

ddDashboardListButtonRef is mistakenly looked for in the ts file, but it shouldn't be there.
It's a valid html element.

**Comment by MeirionHughes** [comment]
published to 0.9.9
