### ISSUE TITLE
Webpack loader

### ISSUE THREAD

**Issue by dweber019** [MeirionHughes/aurelia-template-lint#135]
@MeirionHughes I have created a simple webpack loader with your module as we are running a aurelia boilerplate and had the requirement to have this.

Webpack loader: https://www.npmjs.com/package/aurelia-template-lint-loader
Boilerplate: https://github.com/w3tecch/aurelia-ts-boilerplate

Thanks for your awesome work!

**Comment by MeirionHughes** [comment]
Nice.  :)

Might be worth you locking the dependency to a minor branch, if you've not done so. 0.9 is relatively stable but 0.10 will probably be a breaking change.
