### ISSUE TITLE
0.9.16 package on npm is broken?

### ISSUE THREAD

**Issue by bcanzanella** [MeirionHughes/aurelia-template-lint#137]
It seems like the 0.9.16 package that was released to npm doesn't contain all the required files. For example, the `aurelia-linter.js` file is missing (and a search of the `AureliaLinter` class returns nothing) in 0.9.16.

(0.9.15 is on the left, 0.9.16 on the right)

![915-916](https://cloud.githubusercontent.com/assets/834948/20411162/503d2d26-acee-11e6-9fdb-5f8edbd09151.png)

**Comment by MeirionHughes** [comment]
dam... one sec

**Comment by MeirionHughes** [comment]
try `0.9.17`

**Comment by bcanzanella** [comment]
looks good now! thanks!

**Comment by MeirionHughes** [comment]
sorry, that was really careless of me; I switched from rework branch and forgot for rebuild the files. I've unpublished 0.9.16. Please, keep this open for a few days in case others are affected.
