### ISSUE TITLE
Inherited properties are not supported in static type checking

### ISSUE THREAD

**Issue by 4nderss** [MeirionHughes/aurelia-template-lint#148]
I saw the #68 but in my case I am not using an interface. I am using a base class and I get warnings for my properties declared in my base class.

Example
```
**Base class**
export class BaseItem {
     sharedValue: string = "5";
}

**ViewModel**
export class ExtendedItem extends BaseItem {
     extendedValue: int = 5;
     constructor() {
        super();     
     }
}

**View**
<template>
  <span>${sharedValue}</span>
  <span>${extendedValue}</span>
</template>

```

I get warnings for sharedValue
``` WARNING: cannot find 'sharedValue' in type 'ExtendedItem'```

Or am I missing something?

Using latest version

**Comment by MeirionHughes** [comment]
I will investigate.

**Comment by MeirionHughes** [comment]
Have a look here: https://github.com/MeirionHughes/aurelia-template-lint/commit/74f346297a7c4f2c294a9e9f025269298b0c8c3e
Are you doing anything differently, because that test case works.

**Comment by 4nderss** [comment]
This is our exact case:

list.ts
```
@autoinject()
export class List extends BaseList {
 constructor(
        router: Router,  taskQueue: TaskQueue) {
        super(router, taskQueue);
}
```

baselist.ts
```
export class BaseList {
    constructor(
        public router: Router,
        public taskQueue: TaskQueue) { }
}

list.html
```
<button class="pl-button green block" click.trigger="router.navigateToRoute('new')" tabindex="10">New</button>
...
```

![image](https://cloud.githubusercontent.com/assets/7677245/21174027/1cb7d940-c1db-11e6-8f1c-9b6ab501f209.png)

**Comment by MeirionHughes** [comment]
try `constructor(public router: Router.... )` 

it won't be elevated to a class property without `public/protected/private`

**Comment by 4nderss** [comment]
Because it is public inside the base class wouldn't that make it a duplicate identifier and override the router declared inside baselist.ts ?

**Comment by MeirionHughes** [comment]
yeah your code is fine; I just need to make the constructor lookup traverse into base classes to find what public fields are declared there too.

**Comment by 4nderss** [comment]
Perfecto :) 

By the way props on your work, this is helping us alot!

**Comment by MeirionHughes** [comment]
try 0.9.21

**Comment by 4nderss** [comment]
Works, thanks!

**Comment by timfish** [comment]
I'm using `0.9.23` and its not finding a property on my base class. Could this be due to generics?

```
export class FileDataSource extends BaseDataSource<MemoryStorageMap> {
```
