### ISSUE TITLE
reflectionOpts.sourceFileGlob - support for multiple globs?

### ISSUE THREAD

**Issue by llicht** [MeirionHughes/aurelia-template-lint#154]
Hi,

Currently, reflectionOpts.sourceFileGlob must be a single glob string.
Can support be added for an array of glob strings (similar to how gulp's gulp.src supports an array of glob strings)?

Thanks.

**Comment by MeirionHughes** [comment]
https://github.com/MeirionHughes/aurelia-template-lint/blob/b8fe917b6ce7feabfa1fc03c2325ad1046121d06/source/config.ts#L171-L172

https://github.com/MeirionHughes/aurelia-template-lint/blob/b8fe917b6ce7feabfa1fc03c2325ad1046121d06/example.js#L10

publised: 0.9.22
