### ISSUE TITLE
conflicting attributes even if I use template for the if binding

### ISSUE THREAD

**Issue by timfish** [MeirionHughes/aurelia-template-lint#170]
My code looked like this:
```
    <graph-annotation-hover if.bind="margins && state.bounds" repeat.for="annotation of result.annotations" >...</graph-annotation-hover>
```
And I got the `conflicting attributes` error so I moved the `if` onto a `template`:
```
  <template if.bind="margins && state.bounds">
     <graph-annotation-hover repeat.for="annotation of result.annotations" >...</graph-annotation-hover>
  </template>
```
But still get the error. Am I missing something here, or is this a bug?

**Comment by MeirionHughes** [comment]
hmm bit odd. The code that checks for that seemly only goes over the attributes for a specific element node.

**Comment by timfish** [comment]
Just remembered that template within svg [is broken](https://github.com/aurelia/templating/issues/472) so I cant do this anyway. I'll reopen if I find this happening elsewhere.
