### ISSUE TITLE
Base class properties  not found

### ISSUE THREAD

**Issue by arfilon** [MeirionHughes/aurelia-template-lint#174]
hello , 

thanks for the grate work, on this.

i have these classes 

```
export class Page extends PagedViwe<Ad>  {
}

export abstract class PagedViwe<T> {
    public Items = new Array<T>();
}
```

put i keep getting this validation message 

> cannot find 'Items' in type 'Page'

did i miss something?

thanks

**Comment by jordan-ware** [comment]
I've come across the same issue:
```
interface Interface1
{
    propertyOne: string;
}
interface Interface2 extends Interface1 {
    propertyTwo: string;
}
```
Results in:
> (Emitted value instead of an instance of Error) [46, 33]: cannot find 'propertyOne' in type 'Interface1'
