### ISSUE TITLE
project not compiling, tests failing

### ISSUE THREAD

**Issue by atsu85** [MeirionHughes/aurelia-template-lint#20]
@MeirionHughes, project is not compiling any more, because of the change in `Config.obsoleteTags` array element type - see https://github.com/MeirionHughes/aurelia-template-lint/commit/164690fedf032cb41bfd4d6be23ed8fdbb4b5c7c#diff-e0a6a82d2b4f370ff0e9f57b7667bdd5R6

**Comment by MeirionHughes** [comment]
still? Travis is happy and I'm compiling fine.

**Comment by atsu85** [comment]
My bad, npm update failed for me, now it is working fine
