### ISSUE TITLE
Check that `<slot>` is not inside a template controller

### ISSUE THREAD

**Issue by atsu85** [MeirionHughes/aurelia-template-lint#26]
Based on [this quote from](https://github.com/aurelia/templating/issues/389#issuecomment-226284012) @EisenbergEffect:
> slot inside of an if.bind cannot work because slots themselves have to be statically known

**Comment by atsu85** [comment]
I'll send a PR with a failing test in a moment

**Comment by atsu85** [comment]
I've added two tests - one of them fails, but I don't have time to implement it right now. 

Note: It would help to implement some other rules as well if new base class would be created for the rules, that need to inspect ancestor element attributes (as I understand right now it is easy to check the only tag names of the ancestor elements, but not the attributes).

**Comment by MeirionHughes** [comment]
yes, I can add that info into the ParseNode class if its needed

**Comment by atsu85** [comment]
oh, I didn't notice, that ParseNode was from template-lint, not from parse5 class :)

**Comment by MeirionHughes** [comment]
I'll add this to SlotRule.

requires: https://github.com/MeirionHughes/template-lint/issues/23

**Comment by MeirionHughes** [comment]
@atsu85  Is this just for `if.bind` by the way? any other limitations before I clean up and close?

**Comment by Thanood** [comment]
@MeirionHughes I'm guessing from the recent blog posts about ShadowDOM v1 that this would also affect `repeat.for`. But I've not tested it myself.

**Comment by atsu85** [comment]
>  Is this just for if.bind by the way?

No, for all template controllers (as i've indicated in the test message), so indeed, `repeat.for` should behave exactly like `if.bind`.
