### ISSUE TITLE
Support HTMLElement Type Checking

### ISSUE THREAD

**Issue by MeirionHughes** [MeirionHughes/aurelia-template-lint#38]
Type checking of Element access is currently not implemented.

~~when aurelia-pal-nodejs is implemented ([tracked issue](https://github.com/aurelia/pal-nodejs/issues/1)),~~ we  can use jsdom to create a HTMLElement in memory, based off the tag. Then we can compare the access chain against the actual object.

**Comment by MeirionHughes** [comment]
I honest cannot remember where I saw this kind of usage (where you bind directly to a DOM tree object). Will close for now.

**Comment by atsu85** [comment]
I guess You don't mean the opposite case where ref is bound to field using `ref` attribute?

**Comment by MeirionHughes** [comment]
I thought I saw an example where you could bind to some DOM element/method, but I cannot find anything to confirm that. I'll reopen if someone shows me an example; otherwise I'll assume I was wrong.

**Comment by atsu85** [comment]
Did you mean @children decirator to bind DOM element to viewmodel?
