### ISSUE TITLE
Enchancement to SyntaxRule: allow configuring protected modifier as valid for members used from template

### ISSUE THREAD

**Issue by atsu85** [MeirionHughes/aurelia-template-lint#63]
I have following suggestions related to SyntaxRule and private/protected access checks:
1) when html template uses private/protected variable, and reporting private/protected access violation is enabled, then issue should have WARNING level, not ERROR (because they are not errors at runtime).
2) It should be possible to configure SyntaxRule so that only members with private modifier are reported when used from templates, but not protected modifiers. That is because I'm using following conventions:
* private - only from the same TS class
* protected - from subclasses and templates
* (default aka public) - only aurela lifecycle hooks, `@bindable`,...
* public - fields/methods that really need to be made available to other TS classes

These conventions have served me and my team very well - helps to understand code faster (to make some assumptions during code review for example).

**Comment by atsu85** [comment]
I'll send a PR with tests soon.

**Comment by MeirionHughes** [comment]
I'm in the middle of adding more config options for each reported issue, including having opt-out for private and protected separately.

**Comment by atsu85** [comment]
I just sent a [PR](https://github.com/MeirionHughes/aurelia-template-lint/pull/64) before seeing Your last comment. But it contains couple of additional changes (in separate commits) in addition to 
> having opt-out for private and protected separately.
