### ISSUE TITLE
Add warning when not assigning result of method invocation that returns subscription (that should be disposed)

### ISSUE THREAD

**Issue by atsu85** [MeirionHughes/aurelia-template-lint#81]
**Feature request**
Linter should add warning when it finds a method method invocation, that returns subscription that isn't stored to variable (or returned from the method or passed to another meothd where it could be potentially stored somewhere else). All subscriptions should be disposed to avoid
* memory leaks
* unexpected behavior, such as some event triggering twice and screwing smth up
* performance overhead (subscription callback doing work after it is needed)

When You subscribe to EventAggregator events, it returns subscription object that should be called when component/VM is unbound/deactivated. Following code:
`eventAggregator.subscribe(event, callback);`
should create warning, 
while following:
`this.subscription = eventAggregator.subscribe(event, callback);`
and
`return eventAggregator.subscribe(event, callback);`
and
`storeSubscription(eventAggregator.subscribe(event, callback));`
should be ok.

*Notes*
I'm not sure what is the best way to implement or even test it. As TS has structural types, the linter can't check the return type with instanceof, so probably `subscribe` method name should be hard-coded or be made configurable. It may make sense to check the subscribe method signature as well (including signature used in example and its overloads) to avoid creating warnings for other subscription methods that don't need explicit unsubscription.

**Comment by MeirionHughes** [comment]
I'm not sure about this one; lots of different ways you could still leak without warning.

Seems like the easier solution is to have `EventAggreator` store the subscription disposers via a `WeakMap` that way any gc'ed subscription disposers can be detected. e.g. store disposer in `WeakMap` key with value pointing to event listener object. Periodicity check the WeakMap and match listeners to the WeakMap values. Any listener with no disposables should be removed. @EisenbergEffect thoughts?

**Comment by EisenbergEffect** [comment]
I don't think the EA can keep a list for now since not all browsers support WeakMap and polyfills aren't reliable.

**Comment by MeirionHughes** [comment]
We can maybe revisit this later, but there are so many ways this could still leak; Also some service level stuff might never dispose...

**Comment by atsu85** [comment]
> there are so many ways this could still leak

I know, i just wanted basic check that would detect most common problem (forgetting that smth needs to be done with the subscription)
