### ISSUE TITLE
Binding rule should supports importing any ES6 modules in in any valid form

### ISSUE THREAD

**Issue by atsu85** [MeirionHughes/aurelia-template-lint#85]
#83 fixed one bug related to one way of importing ES6 module, but there are actually [more valid variations](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import) and 2 of them fail even after #83:

```TypeScript
    import defaultMember from "module-name"; // FIXME: Cannot read property 'elements' of undefined
    import * as name from "module-name"; // FIXME: Cannot read property 'findIndex' of undefined
    import "module-name"; // FIXED by #83
    export class Foo{
      existing:string;
    }
```

**Comment by atsu85** [comment]
I'll send a PR with test that reproduces the issue and and fix to this issue shortly.

**Comment by atsu85** [comment]
created a [PR](https://github.com/MeirionHughes/aurelia-template-lint/pull/86) to reseolve this issue

**Comment by atsu85** [comment]
@MeirionHughes, thanks for merging, could You please release as well?

**Comment by MeirionHughes** [comment]
will quickly fix your other issue then will do so .

**Comment by atsu85** [comment]
oh, that's a nice surprise :+1:

**Comment by MeirionHughes** [comment]
yeah sorry; still swamped with main work. I will get around to doing front-end stuff in a few weeks then I can actually start using this linter and work through more issues. :P
