### ISSUE TITLE
TypeError: Cannot read property 'line' of undefined

### ISSUE THREAD

**Issue by atsu85** [MeirionHughes/aurelia-template-lint#92]
**Edit: changed my initial comment after digging deeper**

When i clone and build and link aurelia-template-lint npm module to my project then everything works as expected, but when i do a clean install of gulp-aurelia-template-lint (deleting node_modules before running `npm install`) then i get an error that seems to be related to parsing html/svg elements and its attribute names. 

I suspect that parse5 could be somehow related to this problem:
```
`+-- gulp-aurelia-template-lint@0.9.1
| `-- aurelia-template-lint@0.9.5
|   `-- aurelia-pal-nodejs@1.0.0-alpha.1
|     `-- jsdom@9.4.2
|       `-- parse5@1.5.1
```
but i'm not sure any more, as after manually installing `npm i parse5@2.1.x --save-dev` i have 2 versions (including older parse5@1.5.1), but parse5/package.json visible bellow in stack trace seemed to be the same (@2.1.5)that is installed in aurelia-template-lint as well

```
|   +-- escodegen@1.8.1
|   +-- parse5@1.5.1
+-- parse5@2.1.5
```

but in my project i had 3 versions before running `npm dedupe`.

**So before npm dedupe i got following error (even tough node_modules/parse5 versions in my project and aurelia-template-lint were the same):**
TypeError: Cannot read property 'line' of undefined
    at next.attrs.attrs.map (C:\path\to\aurelia-app\node_modules\aurelia-template-lint\dist\ast.js:26:97)
    at Array.map (native)
    at Parser.parser.on (C:\path\to\aurelia-app\node_modules\aurelia-template-lint\dist\ast.js:22:32)
    at emitMany (events.js:132:20)
    at Parser.emit (events.js:201:7)
    at Parser.SAXParser._handleToken (C:\path\to\aurelia-app\node_modules\template-lint\node_modules\parse5\lib\sax\index.js:171:14)
    at Parser.SAXParser._runParsingLoop (C:\path\to\aurelia-app\node_modules\template-lint\node_modules\parse5\lib\sax\index.js:149:18)
    at Parser.SAXParser._transform (C:\path\to\aurelia-app\node_modules\template-lint\node_modules\parse5\lib\sax\index.js:76:14)
    at Parser.Transform._read (_stream_transform.js:167:10)
    at Parser.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at Parser.Writable.write (_stream_writable.js:220:11)
    at Readable.ondata (_stream_readable.js:556:20)
    at emitOne (events.js:96:13)
    at Readable.emit (events.js:188:7)
    at Readable.read (_stream_readable.js:382:10)
    at flow (_stream_readable.js:762:34)
    at emitReadable_ (_stream_readable.js:434:3)
    at _combinedTickCallback (internal/process/next_tick.js:71:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by atsu85** [comment]
Hmm, looks like I made incorrect assumptions, as I saw cached/outdated diff that included parse5/package.json - real problems must be somewhere else (probably related my html)

**Comment by atsu85** [comment]
I'm reopening, as there seems to be some kind of mess with parse5 versions (2 versions in aurelia-template-lint project).

What i found out, is that when linting after normal installation (without using npm link), then attribute name only contains local name of the attribute - for example for 
```html
      <svg class="icon">
          <use xlink:href="icons.svg#some_selector"></use>
      </svg>
```
ast.ts attribute name field contains only "href" (and there is prefix property, that contains "xlink") while if i run the project after npm link (or from the tests), then name property contains "xlink:href" and there is no prefix property on the attribute.

**Comment by atsu85** [comment]
I'll send a PR shortly to work around the parse5 version difference. @MeirionHughes if You have better suggestions, then I'll listen gladly, but I'm a bit sleepy at the moment (would like to get it solved eventually)

**Comment by atsu85** [comment]
[PR with workaround](https://github.com/MeirionHughes/aurelia-template-lint/issues/93) is ready. 

One more thing to note: I'm running node v6.3.0 and npm 3.10.3 - i thought that they don't need dedupe any more (thought that npm does it now automatically), but probably i'm missing smth.

**Comment by MeirionHughes** [comment]
I think its because you're supposed to use peerDependencies yourself now. 

jsdom uses parse5 1.4 and we use parse5 2.1. Looks like updating jsdom to parse5 2 is slow: https://github.com/tmpvar/jsdom/pull/1316

**Comment by atsu85** [comment]
do You mean, i should put gulp-aurelia-template-lint to peerDependencies instead of devDependencies? (sry, i'm still quite new to npm and JS ecosystem in general)

**Comment by MeirionHughes** [comment]
No no; generally if you want to depend on a package, but not its version you can use peerDependency... this is how a few things with typescript for example (its your job to install a typescript version you want to use. I don't think that applies here because its quite interwind. 

I've had another look and from what I can tell the aurelia-template-lint is defiantly using version 2 and jsdom has a subfolder with version 1.5.1. So it does manage to deal with version mismatches of older dependencies. i.e. cannot be de-duped.

**Comment by atsu85** [comment]
hmm, so gulp-aurelia-template-lint should still be in devDependencies and i should put smth else in my project into peerDependency (probably parse5 or dependency that wants to use parse5, such as jsdom)?

**Comment by MeirionHughes** [comment]
might be able to make pal-nodejs a peerDependency of your other project (the one your linking from). but jsdom defiantly needs 1.5.1 and the linter needs 2.1.x. 

You might be seeing an issue with the module resolution of nodejs itself (linking to a project that has a dependency that cannot be deduped).

**Comment by atsu85** [comment]
so I tried following:
aurelia-app/package.json:
```json
{
...
  "devDependencies": {
    "gulp-aurelia-template-lint": "^0.9.1",
    ...
  },
  "peerDependencies": {
    "aurelia-pal-nodejs": "^1.0.0-alpha.1"
  },
...
}
```

then deleted node_modules and ran `npm install`, that installed 3 versions of parse5:
```
+-- aurelia-bundler@0.3.2
| +-- babel-core@5.8.3
| `-- whacko@0.19.1
|   +-- domutils@1.5.1
|   `-- parse5@1.5.1
+-- gulp-aurelia-template-lint@0.9.1
| `-- aurelia-template-lint@0.9.5
|   +-- parse5@2.1.5
|   +-- template-lint@0.7.7
|   | `-- parse5@2.2.0
```
(Note: aurelia-template-lint and template-lint even want different versions of parse5).

Running gulp task still results in the same error (stacktrace in initial comment) including
```
TypeError: Cannot read property 'line' of undefined
at next.attrs.attrs.map (C:\path\to\aurelia-app\node_modules\aurelia-template-lint\dist\ast.js:26:97)
...
at Parser.SAXParser.handleToken (C:\path\to\aurelia-app\node_modules\template-lint\node_modules\parse5\lib\sax\index.js:171:14)
```
and C:\path\to\aurelia-app\node_modules\template-lint\node_modules\parse5\package.json contains "version": "2.2.0".

@MeirionHughes, am I doing smth wrong?

**Comment by MeirionHughes** [comment]
right there we go... reproduced it.

**Comment by MeirionHughes** [comment]
Still failing for me; I'll fix.

**Comment by MeirionHughes** [comment]
I've reverted both projects to 2.1 and locked can you rimraf your node_modules and reinstall.

**Comment by atsu85** [comment]
doing that right now :+1:

**Comment by atsu85** [comment]
works great, now everything works as expected, even with
`config.debug = true;`

Thanks @MeirionHughes, this project is just fantastic!
