### ISSUE TITLE
lint aurelia-template-lint TS sources and tests

### ISSUE THREAD

**Issue by atsu85** [MeirionHughes/aurelia-template-lint#96]
[TSLint](http://palantir.github.io/tslint) has [rules](http://palantir.github.io/tslint/rules/) to check errors/problems and code style.

**Comment by atsu85** [comment]
I'll send a PR shortly

**Comment by MeirionHughes** [comment]
OK. I generally let vs code format for me. Shame there is no Resharper for TypeScript. :)

**Comment by atsu85** [comment]
> Shame there is no Resharper for TypeScript. :)

IntelliJ WebStorm (and IDEA ultimate) have excellent TypeScript support - that is one of the reasons I now finally decided to make the switch from Eclipse + Atom (made the switch last Friday :))

**Comment by MeirionHughes** [comment]
Yeah; unfortunately I've never been a big fan of jenbrains's intellisense for some reason; Visual Studio and VSCode has always outputted it better in my opinion. Apart from that WebStorm is generally quite good.

**Comment by atsu85** [comment]
The [PR](https://github.com/MeirionHughes/aurelia-template-lint/pull/97) is ready to be merged - i  disabled all rules (generated by tslint --init) that were violated, so take a look at #98
